<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Layout\" />
    <Folder Include="Components\Pages\" />
    <Folder Include="Shared\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RCLAPI\RCLAPI.csproj" />
    <ProjectReference Include="..\RCLCompras\RCLCompras.csproj" />
    <ProjectReference Include="..\RCLImages\RCLImages.csproj" />
    <ProjectReference Include="..\RCLProdutos\RCLProdutos.csproj" />
  </ItemGroup>



</Project>
